
import matplotlib.pyplot as plt
import numpy as np

# creating linspace
x = np.linspace(0, 2 * np.pi, 100)
y_sin = np.sin(x)
y_cos = np.cos(x)

# а)
plt.figure(figsize=(8, 5))
plt.plot(x, y_sin, label='sin(x)', color='red', linestyle='-', marker='o', markersize=4)
plt.plot(x, y_cos, label='cos(x)', color='blue', linestyle='--', marker='x', markersize=4)
plt.title('Синус та косинус на одному графіку')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# б)
fig, axs = plt.subplots(1, 2, figsize=(14, 5))
axs[0].plot(x, y_sin, color='green', linestyle='-', marker='^', markersize=5)
axs[0].set_title('sin(x)')
axs[0].set_xlabel('x')
axs[0].set_ylabel('y')
axs[0].grid(True, linestyle='--', alpha=0.6)
axs[1].plot(x, y_cos, color='purple', linestyle='-.', marker='s', markersize=5)
axs[1].set_title('cos(x)')
axs[1].set_xlabel('x')
axs[1].set_ylabel('y')
axs[1].grid(True, linestyle='--', alpha=0.6)
plt.suptitle('Синус та косинус на одному рисунку, але на різних графіках')
plt.tight_layout()
plt.show()

# в)
plt.figure(figsize=(7, 5))
plt.plot(x, y_sin, color='orange', linestyle='-', marker='d', markersize=6)
plt.title('sin(x) на окремому рисунку')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()
plt.figure(figsize=(7, 5))
plt.plot(x, y_cos, color='brown', linestyle='--', marker='*', markersize=6)
plt.title('cos(x) на окремому рисунку')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()
